Developed GUI 1.0 (#35)
* adding GUI to repo

* removing ascii art as it is no longer needed

* base.html: put header inside the header tag

* put all screens into a single html and made routes.js to work with it

gui_main.py: runs base.html instead of start_screen.html

routes.js: working similarly but the inside code has changed to show and hide screens

base.html: contains all the screens

.gitignore: dev.js for quick fill is kept private

* can show errors to screen

* added version to title for users to know which executable they are using

* hooked up try again button

* giving out error_screen.js with traceback, but the errors can be way too much

* added comments to error_screen.js

* gui working similar to the original excel_uploader_main.py

* using a giant upload_driver that has the exact code as original excel uploader main.py

base.html: added span element to show what is being uploaded

base.html: removed error for data privacy options radio buttons because radio buttons can't really have errors

loading_screen.js: have the code ready to show what is being uploaded

loading_screen.js: using python to navigate to success screen and not when js hits 100% uploaded

excel_uploader_main.py: upload_driver() is exactly the code from original excel uploader main.py

excel_uploader_main.py: upload_to_cript function not currently working or being called

upload.py: putting it back as it originally was for now

* loading screen progress bar working

base.html: changed progress label from span to em because that reads better

excel_uploader_main.py: implemented idea of progress bar with uploads and upload.py and

upload.py: using current_progress, total_progress,

 gui_main.py: updated doc string for update_progress_bar, so it can be easily understood

* excel_uploader_main.py: removed get_parsed_sheet(), create_nodes(), upload_to_cript()

because currently using a giant upload_driver() instead

* built out globus authentication screen in base.html

base.html: built globus authentication screen

routes.js: added goToGlobusAuthScreen() and made code more dry with the addition of hideAllScreens()

globus_screen.js: added js file with function to set the globus url

added secure_login.png for globus auth screen

gui_main.py: after send_to_upload() will call globus_auth() method

excel_uploader_main.py: put get collections url in its own method that can be called easily

* when user closes the app window, the program exits, and added some doc strings to upload.py

gui_main.py: implemented user_closed_app()

all_screens.js: when user closes the app, I call python function to exit the program

base.html: added all_screens.js to head
base.html: removed jinja code because not using jinja anymore

excel_uploader_main.py: retuning at the end of upload part of upload_driver()

upload.py: added doc strings
upload.py: formatted

* updated requirements.txt and requirements_dev.txt

base.html: commented out dev.js for quickFill

* updated requirements for users and dev

* globus screen and js and python functions built out and password visibility toggle works for globus screen and start screen

start_screen.js: added api token visibility toggle

gui_main.py: added placeholder methods for globus

gui_main.py: added doc strings to globus methods

globus_screen.js: added globus token visibility toggle and can submit from frontend to python eel

* base.html some styling on start screen

* works correctly by taking users to error screen when they get an error

* catching cript.exceptions.UnsavedNodeError in upload.py and showing it to the user, but not really handling it

* progressbar resetting from error_screen.js

* progress bar working correctly as it used to

* progress bar working correctly and upload.py upload() setting the variable instead of returning anything

* upload.py: if statement for if using files from web instead of local then dont ask for globus authentication

* going to error screen or globus screen correctly

* removed Try again button in error screen and error list is in excel_uploader_main.py

base.html: commented out try again button for now because the errors persisting in the program can mess it up, and that can be fixed later

styles.css: expanded error-window since there is no Try again button below it

excel_uploader_main.py: maintaining the error_list

* gui works with success_screen

* gui can upload successfully

* gui start screen input labels are all uniform width

* updated requirements_dev.txt

* gui_main.py fixed the path issue so it will work regardless of where in the terminal you are

* removed print statement

* optimized imports and formatted gui_main.py

* pyinstaller_compile.bash script added for compiling code from python with pyinstaller on windows to executable

* removed all other html templates besides base.html because other templates will no longer be used

* updated title to be alpha version

* added instructions to error screen and because of that styles.css and base.html also changed

* progress bar is animated

* data will be kept non-public

base.html: removed private and public option and added "your data will be uploaded as non-public"

start_screen.js: removed js looking for private and public options

gui_main.py: removed setting data privacy and just hard coding it to private

* changed success screen button to CRIPT purple

* made "Authentication Failure" more bold

* added python exit handler so when python is closes the gui closes as well

* changed extension for pyinstaller_compile.sh

* removed !bash from pyinstaller_compile.sh

* changed the path for html_path, minor change

* removed finished TODO about renaming alternative_main.py

* visibility toggle button added changing icons to give feedback of which state it is in

* added JS comments for documentation

* added bash file to compile on windows and ubuntu

* added bash header to pyinstaller_compile_ubuntu.sh

* added github action files for compiling gui in mac, windows, and linux

* added name flag to pyinstaller_compile_windows.sh

* fixed html_path variable

* added visibility icon switching for globus auth screen

* updated create.py and parse.py to what is in develop branch

* changed GUI port to 8001, so it does not clash with anything else running

* worked on globus authentication. initial version is working and can authenticate with globus

gui_main.py: built out the globus_auth() method logic

gui_main.py: updated doc strings

excel_uploader_main.py: updated doc strings

excel_uploader_main.py: changed upload.upload part of upload_driver to reflect updates in GitHub dev branch

excel_uploader_main.py: built out set_globus_auth_link() and is_globus_auth_token_valid()

base.html: removed dev.js script import

base.html: start screen says "Your data will be uploaded as unpublished"

base.html: globus screen added accessibility aria lables

base.html: added validation feedback to globus screen

globus_screen.js: added validation feedback function to globus_screen.js

* redesigned UI for Globus Auth Screen

* added todo to gui_main.py

* takes user to globus correctly if they only have a local file to upload

* removed jinja as a dependency in requirements_dev.txt

* updated requirements.txt and requirements_dev.txt

* GUI compiling successfully, and fixed the html path variable

* removed tqdm from code and requirements_dev.txt

* removed print statements used for debugging

* program compiles successfully

* downgraded the requirements into what it was

* excel_uploader_main.py: updated is_uploading_local_files to use .startswith() instead of just checking if a http is in the whole string

* gui_main.py: initializing eel inside the constructor

* loading_screen.js: stopping progress bar from going over 100%

* Fix data sheet parameters

* excel_uploader_main.py: fixing get_total_for_progress_bar( ) because at the end I added 3 to debug but I forgot to remove it

* added attribution shields to README.md

* fixed material-mkdocs badge

* changed styling for attributions

* updated docs link heading in README.md

* changing start screen back to non-public

* removed the commented out tkinter dialog box cript icon

* added tkinter.destroy() if either the program is closed or python exits

* saving if the dialog box is already open or not, so user cannot open a 100 instances of a dialog box

* removed some solved TODO comments

* formatted src/python/ with black

* removed the terminal command files to compile the GUI to executable

* putting requirements_dev.txt into requirements.txt and removing requirements_dev

This is because users no longer need to pull the code and run a requirements.txt file to run python from their terminal. Instead the only people installing requirements will be developers or advanced users

* removed (alpha) from the top of the GUI since it will be distributed to users and is now versioned as 1.0

* resolving requested changes to merge into master branch

base.html: changed from v1.0 to v0.5

gui_main.py: removed comments about imports

requirements.txt: removed black, eel, pyinstaller, and pre-commit and placed them inside of requirements_dev.txt

excel_uploader_main.py: removed self.data_is_public from __init__()

* resolving requested changes to merge into master branch

removing unused variables from gui_main.py: host, api_key, project_name, collection_name, data_is_public

* adding development branch changes into this branch

* fixed version typo

* cleaned up assets and putting images in /assets/images/ folder

* jazzed up loading screen: added description of things that the program does

* updated README.md badges to include color, logo, and spacing them out

* removing space between badges

* reworded badges from "packages" to "dependencies" and fixed typos

* reworded badges from "packages" to "dependencies" and fixed typos

* spaced out badges for better readability

* removed the extra space. looks better without it

* removed duplicate description badge for loading screen

* "Try Again" button works correctly from the Error screen

base.html: enabled the "Try Again" button and removed the instructional text about telling the user to "close the program and relaunch it"

error_screen.js: created the functions to reset all screens and then call python to clear the error_list and set current_progress to 0

gui_main.py: created a reset_for_uploading() method that empties out the error_list and then calls excel_uploader_main.py to clear out the current_progress for progress bar

* when clicking the "Try Again" button from error_screen, it will clear out any feedback and validation from start_screen so when navigating back there are not any left over feedback

* updating GUI to newest SDK version, but getting errors and more work is needed

add_sample_preparation_to_process() seems to be broken. Getting an error of:

cript.data_model.exceptions.UnsavedNodeError: Experiment nodes must be saved before they can be added to other nodes.

* updating GUI to newest SDK version, but getting an error when adding sample_preparation:

cript.data_model.exceptions.UnsavedNodeError: Process nodes must be saved before they can be added to other nodes.

* skipping Reference Node duplicate uploads

upload.py: if trying to save Reference node that already exists then the program just skips it and continues uploading everything else

excel_uploader_main.py: just removed a comment that is not needed anymore

* added 5 ms of pause between each upload to keep our server safe from DDOS

* remove the pause from between upload calls within excel_uploader_main.py and placed it inside of upload.py between each upload to cript to prevent any DDOS

* changing headers to rows 1-4 because of new Excel file has 4th row as instructions/description and the value starts at row 5

Co-authored-by: Reid Mello <30907815+rjmello@users.noreply.github.com>